#spring:
#  jpa:
#    show-sql: true
#    hibernate.ddl-auto: create-drop
#    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/test-db}
#    username: ${USER:user}
#    password: ${PASSWORD:password}
#    hikari.connection-timeout: 30000
#    driver-class-name: org.postgresql.Driver
#    initialization-mode: always
#  main.allow-bean-definition-overriding: true
#
#logging.level.org.springframework: INFO
server.port: ${PORT:8085}